#!/usr/bin/env python


import lastopt


def install(package, dependencies=False):
    print "install %s, with dependencies: %s" % (
        package, dependencies and 'yes' or 'no')


class Env(object):
    def __init__(self, name):
        self.name = name

    def start(self, package):
        print "starting %s.%s" % (self.name, package)


lastopt.main([install, Env])
